version: "3"

tasks:
    build:
        cmds:
            - swift build

    format:
        cmds:
            - swift format --configuration .swift-format.json --recursive --in-place --parallel Sources/ Tests/ Examples/ Package.swift

    lint:
        cmds:
            - cmd: swiftlint --quiet
              ignore_error: true
            - swift format lint --configuration .swift-format.json --recursive --parallel Sources/ Tests/ Examples/ Package.swift

    package:
        cmds:
            - swift build -c release

    example:
        cmds:
            - swift run {{.CLI_ARGS}}Example
